### PR TITLE
"npm run test-watch": rerun "test" npm script anytime a file changes

### LINKED ISSUE #56: Add test watcher script
Use nodemon or similar tools to add a `npm run test-watch` script that reruns tests as source or test files are updated.

### PR DESCRIPTION
**Pull request by all3fox**
close #56 

Sorry for the delays: midterms have arrived this week :)

### CODE REVIEW

**Comment by jzaefferer** [comment]
Nice, simple enough.

**Comment by jzaefferer** [comment]
Tested this by running `npm run test-watch`, then updated something in `test.js` to break the tests. The output from `standard` and `nodeunit` is fine, but npm also dumps a lot of debug output, starting with this:

```
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/jzaefferer/.nvm/versions/node/v5.3.0/bin/node" "/Users/jzaefferer/.nvm/versions/node/v5.3.0/bin/npm" "run" "test"
npm ERR! node v5.3.0
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE
```
That's unnecessary and misleading, and easily trumps the valid output. Let's figure out a way to hide that.

**Comment by all3fox** [comment]
I have fixed it with the `--silent` flag, the output from "standard" and "nodeunit" is preserved.

**Comment by jzaefferer** [comment]
Nice, that works well. Merged!

**Pull request merged**
