### PR TITLE
Readme and links

### PR DESCRIPTION
**Pull request by all3fox**
* add links to style guides from error messages
* add the `git commit --no-verify` line to readme
* add more cool badges

Are you ok with using shields.io? Even the travis badge looks more sharp :)

Changing error messages showed how not very flexible the tests are. Small change in code -> rather daunting change in tests

### CODE REVIEW

**Comment by jzaefferer** [comment]
How about adding the postfix in the "parent" module, instead of the validation module? That way you have to do it just once, and the tests could stay the same.

**Comment by all3fox** [comment]
Do you mean that many `+ postfix` fragments could be taken out from `jquery.js` and `angular.js` and put as one loop inside `validate.js`? Well, that will still require the same update in tests. Is it worth doing nonetheless?

**Comment by jzaefferer** [comment]
No, I'd put it in here: https://github.com/jzaefferer/commitplease/blob/master/index.js#L14-L21

That would also avoid having the link multiple times.

**Comment by jzaefferer** [comment]
👍

**Pull request merged**
