### PR TITLE
README: add `commitplease master..HEAD` example

### PR DESCRIPTION
**Pull request by all3fox**
Please tell if there are any other things to improve in the README

### CODE REVIEW

**Comment by all3fox** [comment]
Oh, I know, need to explain `.npmrc` too!

**Comment by jzaefferer** [comment]
Ah yes, that would be good to add.

**Comment by jzaefferer** [comment]
Oops, that npmrc support is very wrong, and I didn't bother to check while we were implementing it. Here's a sample `.npmrc`:

```
my-package:flag= enabled
my-package:someurl= http://localhost:5000/
```
So the sample should be:
```
commitplease:nohook= true
```
(I think, never tested this for configuring dependencies)

**Comment by all3fox** [comment]
@jzaefferer I do not follow. We parse `.npmrc` with `ini`, which is the module used by `npm` itself. And the [readme for][1] `ini` says:

> Sections are treated as nested objects. Items before the first heading are saved on the object directly.

So, `[commitplease]` creates a section and then `nohook = true` goes into that section as the setting. And when you `config = ini.parse('.npmrc')`, you get it under `config.commitpleae.nohook`. What you are suggesting with `my-package:flag=enabled` is creating a top-level member in `config` that does not collide with anything else because it is prefixed by the unique package name. But I assume that is what you already use and that is what you want, right? Or would you like to switch to:
```
[my-package]
flag = enable
someurl = http://localhost:5000/
```
Or do we want both? (like, checking `config.commitplease.nohook` first and if it does not exist, checking `commitplease:nohook` as top-level member of `config`)

[1]: https://github.com/npm/ini

**Comment by all3fox** [comment]
I have also been searching for a complex `.npmrc` on github (to see what people usually do) but unfortunately I have yet found just two very simple ones: [first](https://github.com/porchdotcom/swipe-carousel/pull/9/files), [second](https://github.com/brandon-fryslie/mockingbird2/blob/master/.npmrc).

**Comment by jzaefferer** [comment]
I'm going to put together an example with `.npmrc` and `config` property in `package.json` tomorrow.

**Comment by jzaefferer** [comment]
Here's my test: https://gist.github.com/jzaefferer/bca6ce680cc1a0864d4d087637f72ace (ace!)

Result:
```
$ npm test

> npmrc-test@ test /Users/jzaefferer/dev/jzaefferer/commitplease/npmrc-test
> node test.js

npm_package_commitplease_package_hook yes
npm_config_commitplease {"npmrc_group_hook":true}
npm_config_commitplease_npmrc_hook yes
npm_package_config_commitplease_config_hook yes
npm_package_config_commitplease_npmrc_hook yes
npm_config_npmrc_test_commitplease_npmrc_hook yes
```
Since adding `{ "commitplease": { "nohook": true }}` is the official way to configure commitplease, we should find a way to set that same property via npm. In my test, `npm_package_commitplease_package_hook` is the `process.env` property resulting from that "official" config.

I currently don't see how to produce the same thing with `.npmrc`. Any ideas?

**Comment by all3fox** [comment]
> I currently don't see how to produce the same thing with .npmrc. Any ideas?

I assume you want to produce `npm_package_commitplease_package_hook yes` by setting it somewhere outside of `package.json`

I'd say there is no way to do that because `npm` apparently prefixes variables with `npm_package`  when they come from `package.json` and with `npm_config` when from `.npmrc` (and other places, see below). I see how you tried to `"config": {"commitplease-config-hook": "yes"}` but that still got prefixed with `npm_package` resulting in `npm_package_config_commitplease_config_hook`

Some reading brought me to [npm config][1] which allows you to do this:

```
$ npm config set commitplease:cmdline-hook yes
```

If you do it and run `$ npm test`, then you see a new entry:

```
npm_config_commitplease_cmdline_hook yes
```
Which still gets prefixed with `npm_config` and not `npm_package`. So, it seems you could overwrite `.npmrc` (but not `package.json`) from the commandline.

Do you rely on getting configs from `process.env` instead of parsing (many scattered) config files directly?

[1]: https://docs.npmjs.com/misc/config

**Comment by jzaefferer** [comment]
Doesn't look like `npm config` is the answer either. Let's stick with our existing implementation. That works and shouldn't collide with anything.

Let's land this.

**Pull request merged**
